### ISSUE TITLE
Mod not able to be uninstalled or disabled.

### ISSUE THREAD

**Issue by juniortivotyro** [emulamer/BeatOn#30] opened 2019-07-12 21:01 UTC
https://www.youtube.com/watch?v=7lyPp_gMzTc&feature=youtu.be

Upgraded from 0.0.8.2

Deleting/Disabling other mods works.

Let me know if you need any other info.

**Comment by xAgent42x** [comment] 2019-07-13 16:43
That particular mod plus a few others are causing some issues but this should be fixed in the next build.

**Comment by KarlDeux** [comment] 2019-07-16 15:05
@juniortivotyro @xAgent42x is this issue solved now?

**Comment by xAgent42x** [comment] 2019-07-16 15:40
This should be resolved with 0.0.9.8. Update beat on and see if the issue is resolved.

**Comment by KarlDeux** [comment] 2019-07-18 15:05
I'm closing it since we have no way to reproduce it.

**Closed by KarlDeux** 2019-07-18 15:05 UTC
Labels: bug, question
